import { createRoot } from 'react-dom/client'
import { useState } from 'react'
import { Activity, AlertTriangle, CheckCircle2, CloudLightning, Gauge, Menu, Radio, ShieldCheck, Sparkles, TrendingDown } from 'lucide-react'
import { calculateEtr, formatClock, formatDuration, type EtrInputs } from './etr'
import './styles.css'
import './calculation.css'
import './operations.css'

type View = 'incidents'|'performance'|'watch'|'health'
type Incident = { id:string; area:string; customers:number; cause:string; confidence:'High'|'Medium'|'Low'; status:string; oms:string; inputs:EtrInputs }
const base={referenceMinutes:703,dayNightMultiplier:.96,weatherTravelMultiplier:1.05,weatherRepairMultiplier:1.04}
const incidents:Incident[]=[
  {id:'INC-49287',area:'Wattle Park',customers:1240,cause:'Broken pole',confidence:'Medium',status:'Crew on site',oms:'4:00 pm',inputs:{...base,baseTravelMinutes:34,baseRepairMinutes:161,switchingMinutes:18,operationalZone:'North-east operational zone',operationalZoneMultiplier:1.18,trafficMultiplier:1.15,repairCauseMultiplier:1.13,assetDamageMultiplier:1.18,accessMultiplier:1.11,crewAvailabilityMultiplier:1.02,incidentEscalationMultiplier:1.08,dispatchDelayMinutes:0,backfeedCreditMinutes:0,faultLocationConfidence:.82,uncertainty:.19,materialDelayMinutes:14}},
  {id:'INC-49291',area:'North Ridge',customers:386,cause:'Vegetation',confidence:'High',status:'Crew en route',oms:'3:40 pm',inputs:{...base,baseTravelMinutes:28,baseRepairMinutes:104,switchingMinutes:12,operationalZone:'Central operational zone',operationalZoneMultiplier:1.02,trafficMultiplier:1.08,weatherTravelMultiplier:1.01,weatherRepairMultiplier:1,repairCauseMultiplier:1.05,assetDamageMultiplier:1,accessMultiplier:.96,crewAvailabilityMultiplier:1,incidentEscalationMultiplier:1,dispatchDelayMinutes:8,backfeedCreditMinutes:22,faultLocationConfidence:.91,uncertainty:.12,materialDelayMinutes:0}},
  {id:'INC-49272',area:'Lakeside',customers:87,cause:'Unknown fault',confidence:'Low',status:'Investigating',oms:'2:30 pm',inputs:{...base,baseTravelMinutes:25,baseRepairMinutes:92,switchingMinutes:8,operationalZone:'South operational zone',operationalZoneMultiplier:1.11,trafficMultiplier:1.1,weatherTravelMultiplier:1.03,weatherRepairMultiplier:1.03,repairCauseMultiplier:1.08,assetDamageMultiplier:1,accessMultiplier:1.04,crewAvailabilityMultiplier:1.14,incidentEscalationMultiplier:1.08,dispatchDelayMinutes:24,backfeedCreditMinutes:0,faultLocationConfidence:.42,uncertainty:.35,materialDelayMinutes:15}}
]

function App(){const [view,setView]=useState<View>('incidents');const [selected,setSelected]=useState(incidents[0]);const [menu,setMenu]=useState(false);const label={incidents:'Active incidents',performance:'Performance',watch:'Event watch',health:'Model health'}[view];return <div className="app-shell"><aside className={menu?'sidebar sidebar-open':'sidebar'}><div className="brand"><div className="brand-mark"><Activity size={19}/></div><span>etr<span>confidence</span></span></div><nav><Nav icon={<Radio size={18}/>} label="Active incidents" active={view==='incidents'} onClick={()=>setView('incidents')} badge="3"/><Nav icon={<Activity size={18}/>} label="Performance" active={view==='performance'} onClick={()=>setView('performance')}/><Nav icon={<CloudLightning size={18}/>} label="Event watch" active={view==='watch'} onClick={()=>setView('watch')}/><Nav icon={<ShieldCheck size={18}/>} label="Model health" active={view==='health'} onClick={()=>setView('health')}/></nav><div className="sidebar-bottom"><div className="live-dot"/>Live shadow mode</div></aside>{menu&&<button className="overlay" onClick={()=>setMenu(false)}/>}<main><header><div className="mobile-brand"><button onClick={()=>setMenu(!menu)}><Menu size={22}/></button><span>etr<span>confidence</span></span></div><div className="context"><span className="eyebrow">Operations intelligence</span><h1>{label}</h1></div><div className="header-right"><span className="updated"><span className="pulse"/>Updated 11:43 am</span><div className="avatar">SP</div></div></header>{view==='incidents'?<Incidents selected={selected} select={setSelected}/>:<Operations view={view}/>}</main></div>}
function Nav({icon,label,active,onClick,badge}:{icon:React.ReactNode;label:string;active:boolean;onClick:()=>void;badge?:string}){return <button className={active?'active':''} onClick={onClick}>{icon}{label}{badge&&<em>{badge}</em>}</button>}
function Incidents({selected,select}:{selected:Incident;select:(item:Incident)=>void}){const e=calculateEtr(selected.inputs);return <><section className="stat-row"><Stat icon={<AlertTriangle/>} label="Active outages" value="3" sub="1,713 customers affected" tone="amber"/><Stat icon={<Sparkles/>} label="ETRs recalibrated" value="7" sub="in the past hour" tone="blue"/><Stat icon={<TrendingDown/>} label="Mean absolute error" value="−21%" sub="vs OMS estimate · last 30 days" tone="green"/><Stat icon={<CheckCircle2/>} label="P80 calibration" value="82%" sub="target: 80%" tone="violet"/></section><section className="workspace"><div className="incident-list card"><div className="section-title"><div><span className="eyebrow">Priority queue</span><h2>Live outage view</h2></div></div>{incidents.map(i=><button className={i.id===selected.id?'incident selected':'incident'} onClick={()=>select(i)} key={i.id}><span className={`risk-dot ${i.confidence==='Low'?'low':i.confidence==='Medium'?'medium':'high'}`}/><div className="incident-core"><strong>{i.id}</strong><span>{i.area}</span></div><div className="incident-meta"><strong>{i.customers.toLocaleString()}</strong><span>customers</span></div></button>)}</div><div className="detail"><div className="detail-heading"><div><span className="eyebrow">{selected.id} · {selected.area}</span><h2>{selected.cause}<span className={`badge ${selected.confidence.toLowerCase()}`}>{selected.confidence} confidence</span></h2><p>{selected.customers.toLocaleString()} customers affected · {selected.status}</p></div></div><section className="estimate-grid"><Estimate label="Recommended customer ETR" value={formatClock(selected.inputs.referenceMinutes+e.p80Minutes)} sub="80% confidence by this time" primary/><Estimate label="Operational ETR · P50" value={formatClock(selected.inputs.referenceMinutes+e.p50Minutes)} sub={`Likely window: ${e.range}`}/><Estimate label="Current OMS estimate" value={selected.oms} sub="Model is recalibrating from live events"/></section><section className="explanation-card"><div className="explanation-icon"><Sparkles size={21}/></div><div><span className="eyebrow">Why this changed</span><h3>Live incident and operational context has been recalculated.</h3><p>Travel, repair, access, crew, weather and fault-location confidence are reflected in the current estimate.</p></div></section><Calculation inputs={selected.inputs} travel={e.travelMinutes} repair={e.repairMinutes} total={e.p50Minutes}/></div></section></>}
function Operations({view}:{view:Exclude<View,'incidents'>}){const data={performance:<Performance/>,watch:<Watch/>,health:<Health/>};return <div className="operations-view">{data[view]}</div>}
function Performance(){return <><section className="stat-row"><Stat icon={<TrendingDown/>} label="ETR MAE" value="38 min" sub="21% lower than OMS" tone="green"/><Stat icon={<CheckCircle2/>} label="On-time P80s" value="82%" sub="target: 80%" tone="violet"/><Stat icon={<Activity/>} label="Incidents evaluated" value="4,328" sub="last 30 days" tone="blue"/><Stat icon={<Gauge/>} label="Customer contacts avoided" value="1,140" sub="estimated this month" tone="amber"/></section><section className="ops-grid"><Panel title="ETR accuracy by incident type"><Bars items={[['Vegetation',78],['Equipment failure',71],['Weather damage',63],['Unknown fault',49]]}/></Panel><Panel title="P50 error trend"><div className="trend"><span>Mar<br/><b>54m</b></span><span>Apr<br/><b>48m</b></span><span>May<br/><b>43m</b></span><span>Jun<br/><b>38m</b></span><span className="good">Improving<br/><b>−30%</b></span></div></Panel></section><Panel title="Where the model is adding value"><table><tbody><tr><th>Operational zone</th><th>OMS MAE</th><th>ETR Confidence MAE</th><th>Improvement</th></tr><tr><td>North-east</td><td>55 min</td><td>39 min</td><td>−29%</td></tr><tr><td>Central</td><td>41 min</td><td>30 min</td><td>−27%</td></tr><tr><td>South</td><td>62 min</td><td>49 min</td><td>−21%</td></tr></tbody></table></Panel></>}
function Watch(){return <><section className="stat-row"><Stat icon={<CloudLightning/>} label="Active weather windows" value="2" sub="next 48 hours" tone="amber"/><Stat icon={<AlertTriangle/>} label="Risk-weighted customers" value="8,460" sub="across three zones" tone="violet"/><Stat icon={<Activity/>} label="Pre-event inspections" value="14" sub="recommended today" tone="blue"/><Stat icon={<ShieldCheck/>} label="Readiness score" value="76%" sub="moderate readiness" tone="green"/></section><section className="watch-list"><WatchCard title="North-east wind event" timing="Today · 4:00–9:00 pm" severity="High" text="Gusts to 78 km/h. Elevated vegetation contact risk on 18 feeders." actions="Stage 4 vegetation crews · validate 6 recloser telemetry feeds"/><WatchCard title="Southern rainfall band" timing="Tomorrow · 6:00 am–1:00 pm" severity="Medium" text="Access delays likely for rural repairs and flood-prone crossings." actions="Pre-position materials · shift travel-time multiplier to 1.22×"/><WatchCard title="Heat and peak load" timing="Tomorrow · 2:00–7:00 pm" severity="Medium" text="Higher transformer loading and customer impact if an outage occurs." actions="Monitor 12 high-load transformers · reserve mobile generation"/></section></>}
function Health(){return <><section className="stat-row"><Stat icon={<CheckCircle2/>} label="Overall health" value="Healthy" sub="all safety checks passing" tone="green"/><Stat icon={<Gauge/>} label="Calibration" value="82%" sub="P80 coverage · target 80%" tone="violet"/><Stat icon={<Activity/>} label="Data freshness" value="97%" sub="sources updated within 5 min" tone="blue"/><Stat icon={<AlertTriangle/>} label="Drift alerts" value="1" sub="South-zone travel time" tone="amber"/></section><section className="ops-grid"><Panel title="Model checks"><Checks items={[['P50 bias','Within tolerance','pass'],['P80 coverage','82% vs 80% target','pass'],['Incident taxonomy','94% mapped','pass'],['South-zone travel','7% under-prediction','warn']]}/></Panel><Panel title="Data-source freshness"><Checks items={[['OMS incident feed','42 seconds ago','pass'],['Crew status feed','1 min ago','pass'],['Weather forecast','4 min ago','pass'],['Traffic feed','12 min ago','warn']]}/></Panel></section><Panel title="Recommended calibration action"><div className="recommendation"><Gauge size={22}/><div><b>Review South operational-zone travel coefficient</b><p>Recent completions indicate the current coefficient underestimates travel time by 7% during weekday peak periods. Hold the existing rule for operations and submit a proposed 1.11× → 1.19× change for analyst approval.</p></div></div></Panel></>}
function Calculation({inputs,travel,repair,total}:{inputs:EtrInputs;travel:number;repair:number;total:number}){return <section className="calculation card"><div className="section-title"><div><span className="eyebrow">ADMS-aligned calculation</span><h2>Transparent ETR drivers</h2></div><span className="rule-chip">Ruleset v0.1</span></div><div className="formula"><span>Dispatch</span><b>{formatDuration(inputs.dispatchDelayMinutes)}</b><i>+</i><span>Travel</span><b>{formatDuration(travel)}</b><i>+</i><span>Repair</span><b>{formatDuration(repair)}</b><i>+</i><span>Switching</span><b>{formatDuration(inputs.switchingMinutes)}</b><i>−</i><span>Backfeed</span><b>{formatDuration(inputs.backfeedCreditMinutes)}</b><i>=</i><strong>{formatDuration(total)}</strong></div><div className="driver-grid"><Driver label="Operational zone" value={inputs.operationalZone}/><Driver label="Zone travel multiplier" value={`${inputs.operationalZoneMultiplier.toFixed(2)}×`}/><Driver label="Traffic multiplier" value={`${inputs.trafficMultiplier.toFixed(2)}×`}/><Driver label="Day / night multiplier" value={`${inputs.dayNightMultiplier.toFixed(2)}×`}/><Driver label="Weather multiplier" value={`${inputs.weatherTravelMultiplier.toFixed(2)}×`}/><Driver label="Fault-location confidence" value={`${Math.round(inputs.faultLocationConfidence*100)}%`}/></div></section>}
function Estimate({label,value,sub,primary}:{label:string;value:string;sub:string;primary?:boolean}){return <div className={`estimate ${primary?'primary':''}`}><span className="eyebrow">{label}</span><strong>{value}</strong><p>{sub}</p></div>}
function Stat({icon,label,value,sub,tone}:{icon:React.ReactNode;label:string;value:string;sub:string;tone:string}){return <div className="stat card"><div className={`stat-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>}
function Driver({label,value}:{label:string;value:string}){return <div className="driver"><span>{label}</span><strong>{value}</strong></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel card"><div className="section-title"><h2>{title}</h2></div>{children}</section>}
function Bars({items}:{items:[string,number][]}){return <div className="bars">{items.map(([label,value])=><div key={label}><span>{label}</span><i><b style={{width:`${value}%`}}/></i><strong>{value}%</strong></div>)}</div>}
function Checks({items}:{items:[string,string,'pass'|'warn'][]}){return <div className="checks">{items.map(([name,value,state])=><div key={name}><span className={state}>{state==='pass'?'✓':'!'}</span><b>{name}</b><small>{value}</small></div>)}</div>}
function WatchCard({title,timing,severity,text,actions}:{title:string;timing:string;severity:string;text:string;actions:string}){return <section className="watch-card card"><div><span className={`severity ${severity.toLowerCase()}`}>{severity}</span><h2>{title}</h2><p>{timing}</p></div><div><p>{text}</p><strong>Recommended: {actions}</strong></div></section>}
createRoot(document.getElementById('root')!).render(<App />)
